#!/bin/sh

# Installs dotfiles

if arch

pacman -S --noconfirm \
  sddm \
  neovim \
  vifm \
  stow \
  alacritty \
  picom \
  rofi \
  zip \
  unzip \
  curl \

  light \
  blueman?
  kdeconnect?
  kde-spectacle?
  networkmanager-gnome?
  mpv
  openssh
  zen?
  code?
  awesome!!

  grub


mkdir /usr/share/fonts
cp fonts/* /usr/share/fonts

systemctl enable sddm
systemctl enable sshd

/sbin/reboot



